apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-k8s-controller-config
  namespace: kube-system
data:
  allow-snippet-annotations: "false"
  client-body-buffer-size: 128k
  enable-multi-accept: "false"
  enable-underscores-in-headers: "true"
  log-format-escape-json: "true"
  log-format-upstream: '{"time_date": "$time_iso8601", "client": "$remote_addr", "host":
    "$http_host", "scheme": "$scheme", "request_method": "$request_method", "request_uri":
    "$uri", "request_id": "$request_id", "status": $status, "upstream_addr": "$upstream_addr",
    "upstream_status": $sanitized_upstream_status, "request_time": $request_time,
    "upstream_response_time": $sanitized_upstream_response_time, "upstream_connect_time":
    $sanitized_upstream_connect_time, "upstream_header_time": $sanitized_upstream_header_time}'
  map-hash-bucket-size: "128"
  max-worker-connections: "64510"
  proxy-body-size: 2m
  proxy-ssl-location-only: "true"
  server-name-hash-bucket-size: "1024"
  server-name-hash-max-size: "16384"
  server-tokens: "false"
  ssl-ciphers: HIGH:!aNULL:!MD5:!CAMELLIA:!AESCCM:!ECDH+CHACHA20:!ARIA:!CBC:!SHA1:!SHA256:!SHA384:!DHE-RSA-CHACHA20-POLY1305:!GOST2001-GOST89-GOST89:!GOST2012256-GOST89-GOST89
  ssl-session-cache: "true"
  ssl-session-cache-size: 10m
