---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-prometheus-adapter
data:
  config.yaml: |
    rules:
      - seriesQuery: '{__name__=~"^nginx_ingress_controller_requests.*",namespace!="",ingress!=""}'
        resources:
          overrides:
            ingress: {group: "networking.k8s.io", resource: "ingress"}
            namespace: {resource: "namespace"}
        name:
          matches: ""
          as: "nginx_ingress_controller_requests_rate"
        metricsQuery: "round(sum(irate(<<.Series>>{controller_pod=~\".*\",controller_class=~\".*\",controller_namespace=~\".*\",ingress=~\".*\"}[1m])) by (ingress), 0.001)"
