---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alb-autoscale-example
commonLabels:
  app.kubernetes.io/part-of: alb-autoscale-example
  app.kubernetes.io/name: prometheus-adapter
resources:
- apiservice.yaml
- cluster-role-binding-auth-delegator.yaml
- cluster-role-binding-resource-reader.yaml
- cluster-role-resource-reader.yaml
- configmap.yaml
- custom-metrics-cluster-role.yaml
- deployment.yaml
- role-binding-auth-reader.yaml
- service-account.yaml
- service.yaml
