---
apiVersion: v1
kind: Service
metadata:
  name: alb-prometheus-adapter
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: alb-autoscale-example
  type: ClusterIP