# This policy allows outgoing network traffic from worker nodes to other IBM Cloud services.
# The example nets and ports in this policy are for IBM Cloud Container Registry, IBM Cloud
# Monitoring with Sysdig, IBM Log Analysis with LogDNA, and the managed Istio add-on.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-services
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 169.60.98.80/29
      - 169.62.37.240/29
      - 169.63.104.232/29
      # IBM Cloud Container Registry: AP North, Osaka nets for your own registry
      - 163.68.67.32/28
      - 163.69.67.0/28
      - 163.73.67.64/28
      - 161.202.146.80/29
      - 128.168.71.64/29
      - 165.192.71.216/29
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: AP North nets
      - 128.168.75.14/32
      - 128.168.91.236/32
      - 128.168.91.238/32
      - 161.202.93.250/32
      - 161.202.93.252/32
      - 165.192.69.125/32
      - 165.192.71.227/32
      - 165.192.84.14/32
      - 169.38.128.166/32
      - 169.38.82.173/32
      - 169.56.51.238/32
      - 169.56.80.178/32
      - 169.56.80.182/32
      ports:
      - 6443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: AP North nets
      - 128.168.70.51/32
      - 128.168.70.53/32
      - 161.202.67.2/32
      - 161.202.93.253/32
      - 165.192.69.122/32
      - 165.192.71.226/32
      - 169.38.128.164/32
      - 169.38.82.170/32
      - 169.56.70.102/32
      - 169.56.70.98/32
      ports:
      - 443
      - 80
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      ports:
      # Managed Istio add-on: Egress gateway
      - 80
      - 15443
    protocol: TCP
    source: {}
  ingress:
  - action: Allow
    destination:
      ports:
      # Managed Istio add-on: Ingress gateway and istiod control plane
      - 443
      - 853
      - 15010
      - 15012
      - 15014
      # Managed Istio add-on: Knative cluster local gateway
      - 80
      - 15021
      - 15443
    protocol: TCP
    source: {}
  order: 1800
  selector: ibm.role == 'worker_public'
  types:
  - Egress
  - Ingress
