apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: alb-autoscale-example
resources:
- default
- kube-system
