---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alb-autoscale-example
commonLabels:
  app.kubernetes.io/part-of: alb-autoscale-example
  app.kubernetes.io/name: alb-autoscale-example-app
resources:
- example-deployment.yaml
- example-service.yaml
- example-ingress.yaml
