# This policy allows outgoing network traffic from pods to other
# IBM Cloud services that support private service endpoints.
# The example nets in this policy are for IBM Cloud Container Registry,
# IBM Cloud Monitoring with Sysdig, and IBM Log Analysis with LogDNA.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-private-services-pods
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 166.9.20.31/32
      - 166.9.22.22/32
      - 166.9.24.16/32
      # IBM Cloud Container Registry: UK South nets for your own registry
      - 166.9.34.12/32
      - 166.9.36.19/32
      - 166.9.38.14/32
      # IBM Cloud Container Registry: New Global registry
      - 166.9.251.49/32
      - 166.9.251.82/32
      - 166.9.251.113/32
      # IBM Cloud Container Registry: New UK South nets for your own registry
      - 166.9.244.9/32
      - 166.9.244.45/32
      - 166.9.244.73/32
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: eu-gb
      # Taken from: https://cloud.ibm.com/docs/monitoring?topic=monitoring-endpoints
      - 166.9.34.56/32
      - 166.9.36.71/32
      ports:
      - 6443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: eu-gb
      # Taken from: https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-endpoints
      - 166.9.34.2/32
      - 166.9.34.4/32
      - 166.9.36.2/32
      - 166.9.36.3/32
      - 166.9.38.4/32
      - 166.9.38.5/32
      ports:
      - 80
      - 443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: EU GB nets
      - 166.9.34.18/32
      - 166.9.36.5/32
      - 166.9.38.20/32
      ports:
      - 514
      - 6514
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: EU GB nets
      - 166.9.34.19/32
      - 166.9.36.6/32
      - 166.9.38.21/32
      ports:
      - 514
    protocol: UDP
    source: {}
  order: 1900
  selector: projectcalico.org/orchestrator == 'k8s'
  types:
  - Egress
