# This policy allows outgoing network traffic from worker nodes to other
# IBM Cloud services that support private service endpoints.
# The example nets in this policy are for IBM Cloud Container Registry,
# IBM Cloud Monitoring with Sysdig, and IBM Log Analysis with LogDNA.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-private-services
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 166.9.20.31/32
      - 166.9.22.22/32
      - 166.9.24.16/32
      # IBM Cloud Container Registry: AP South nets for your own registry
      - 166.9.52.20/32
      - 166.9.54.19/32
      - 166.9.56.13/32
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: AU Syd nets
      - 166.9.52.27/32
      - 166.9.54.27/32
      - 166.9.56.32/32
      ports:
      - 6443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: AU Syd nets
      - 166.9.56.3/32
      - 166.9.52.2/32
      - 166.9.56.20/32
      - 166.9.52.5/32
      ports:
      - 80
      - 443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: AU Syd nets
      - 166.9.56.22/32
      - 166.9.52.8/32
      ports:
      - 514
      - 6514
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: AU Syd nets
      - 166.9.56.23/32
      - 166.9.52.9/32
      ports:
      - 514
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM ATracker API : AU Syd
      - 166.9.54.51/32
      - 166.9.56.53/32
      - 166.9.52.48/32
      # IBM ATracker Ingester : AU Syd
      - 166.9.52.49/32
      - 166.9.56.54/32
      - 166.9.54.52/32
      ports:
      - 443
    protocol: TCP
    source: {}
  order: 1900
  selector: ibm.role == 'worker_private'
  types:
  - Egress
