apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alb-autoscale-example
resources:
- service-account.yaml
- deployment.yaml
- service.yaml
- role.yaml
- role-binding.yaml
images:
- name: prom/prometheus
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml
