# This policy allows outgoing network traffic from pods to other IBM Cloud services.
# The example nets and ports in this policy are for IBM Cloud Container Registry, IBM Cloud
# Monitoring with Sysdig, IBM Log Analysis with LogDNA, and the managed Istio add-on.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-services-pods
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 169.60.98.80/29
      - 169.62.37.240/29
      - 169.63.104.232/29
      - 169.47.153.160/28 
      # IBM Cloud Container Registry: AP South nets for your own registry
      - 168.1.1.240/29
      - 130.198.88.128/29
      - 135.90.66.48/29
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: AU Syd nets
      - 130.198.79.42/32
      - 130.198.80.155/32
      - 130.198.89.46/32
      - 135.90.70.74/32
      - 135.90.70.77/32
      - 135.90.73.100/32
      - 168.1.213.78/32
      - 168.1.30.131/32
      - 168.1.38.93/32
      ports:
      - 6443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: AU Syd nets
      - 130.198.89.43/32
      - 130.198.89.45/32
      - 135.90.67.187/32
      - 135.90.70.75/32
      - 168.1.38.90/32
      - 168.1.38.92/32
      ports:
      - 443
      - 80
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      ports:
      # Managed Istio add-on: Egress gateway
      - 80
      - 15443
    protocol: TCP
    source: {}
  order: 1800
  selector: projectcalico.org/orchestrator == 'k8s'
  types:
  - Egress
