# This policy allows outgoing network traffic from worker nodes in each zone of
# your cluster to the cluster master through the public service endpoint. Note
# that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for AP South: mel01, syd01, syd04, syd05
      - 130.198.64.19/32
      - 130.198.66.26/32
      - 135.90.69.66/32
      - 135.90.69.82/32
      - 168.1.8.195/32
      - 168.1.12.98/32
      - 168.1.97.67/32
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for AP South: mel01, syd01, syd04, syd05
      - 130.198.64.19/32
      - 130.198.66.26/32
      - 135.90.69.66/32
      - 135.90.69.82/32
      - 168.1.8.195/32
      - 168.1.12.98/32
      - 168.1.97.67/32
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_public'
  types:
  - Egress
