apiVersion: v1
kind: ServiceAccount
metadata:
 name: tiller
 namespace: kube-system
imagePullSecrets: 
- name: kube-system-au-icr-io
- name: kube-system-de-icr-io
- name: kube-system-jp-icr-io
- name: kube-system-icr-io
- name: kube-system-uk-icr-io
- name: kube-system-us-icr-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: tiller
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
 - kind: ServiceAccount
   name: tiller
   namespace: kube-system
