# ******************************************************************************
# * Licensed Materials - Property of IBM
# * IBM Cloud Kubernetes Service, 5737-D43
# * (C) Copyright IBM Corp. 2020, 2021 All Rights Reserved.
# * US Government Users Restricted Rights - Use, duplication or
# * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# ******************************************************************************
# This policy is used by the audit webhook to collect and forward any events that are passed
# through your Kubernetes API server to IBM Log Analysis with LogDNA. For more information,
# see the docs: https://cloud.ibm.com/docs/containers?topic=containers-health#webhook_logdna

{% if k8s_release_style is version_compare('1.14', '>=') %}
apiVersion: audit.k8s.io/v1
{% else %}
apiVersion: audit.k8s.io/v1beta1
{% endif %}
kind: Policy
rules:
  - level: None
    userGroups: ["system:serviceaccounts:kube-system"]
  - level: None
    # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
    users: ["system:unsecured"]
    namespaces: ["kube-system"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["configmaps"]
  - level: None
    users: ["kubelet"] # legacy kubelet identity
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get", "patch"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["secrets"]
  - level: None
    users:
      - system:kube-controller-manager
      - system:kube-scheduler
      - system:serviceaccount:kube-system:endpoint-controller
    verbs: ["get", "update"]
    namespaces: ["kube-system"]
    resources:
      - group: "" # core
        resources: ["endpoints"]
  - level: None
    users: ["system:apiserver"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["namespaces"]
  # Don't log these read-only URLs.
  - level: None
    nonResourceURLs:
      - /healthz*
      - /version
{% if k8s_release_style is version_compare('1.14', '<') %}
      - /swagger*
{% endif %}
      - /openapi/v2*
{% if k8s_release_style is version_compare('1.16', '>=') %}
      - /readyz*
      - /livez*
{% endif %}
  # Don't log events requests.
  - level: None
    resources:
      - group: "" # core
        resources: ["events"]
{% if k8s_release_style is version_compare('1.19', '>=') %}
      - group: "events.k8s.io"
        resources: ["events"]
{% endif %}        
  # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
  # so only log at the Metadata level.
  - level: Metadata
    resources:
      - group: ""  # core
        resources: ["secrets", "configmaps"]
      - group: authentication.k8s.io
        resources: ["tokenreviews"]
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["pods", "replicacontrollers", "container"]
      - group: "apps"
        resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
      - group: "batch"
        resources: ["jobs", "cronjobs"]
      - group: "extensions" # necessary for pre-1.12 clusters
        resources: ["daemonsets", "deployments", "replicasets"]
{% if k8s_release_style is version_compare('1.19', '>=') %}
  # Log changes to Calico resources
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: crd.projectcalico.org
{% endif %}
  # Excludes the following apigroups from logs
  - level: None
    resources:
      - group: "apiregistration.k8s.io"
      - group: "coordination.k8s.io"
  # Get responses can be large; skip them.
  - level: Metadata
    verbs: ["create", "update", "delete", "patch"]
