# ******************************************************************************
# * Licensed Materials - Property of IBM
# * IBM Cloud Kubernetes Service, 5737-D43
# * (C) Copyright IBM Corp. 2021, 2025 All Rights Reserved.
# * US Government Users Restricted Rights - Use, duplication or
# * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# ******************************************************************************
# This policy is used by the audit webhook to collect and forward any events that are passed
# through your Kubernetes API server to IBM Log Analysis with LogDNA. For more information,
# see the docs: https://cloud.ibm.com/docs/containers?topic=containers-health#webhook_logdna

{% if k8s_release_style is version_compare("1.29", "<=") %}
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["pods", "replicacontrollers", "container"]
      - group: "apps"
        resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
      - group: "batch"
        resources: ["jobs", "cronjobs"]
      - group: "extensions" # necessary for pre-1.12 clusters
        resources: ["daemonsets", "deployments", "replicasets"]
  # Log changes to Calico resources
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: crd.projectcalico.org
  # Log everything not covered above as Metadata
  - level: Metadata

{% else %}
# This policy is copied from openshift's audit policy https://github.com/openshift/library-go/tree/master/pkg/operator/apiserver/audit/manifests
# Where base-policy.yaml is combined with writerequestbodies-rules.yaml.
apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  name: policy
# drop managed fields from audit, this is at global scope.
omitManagedFields: true
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
- "RequestReceived"
rules:
{% if k8s_release_style is version_compare("1.31", "<=") %}
# Don't log requests for events
- level: None
  resources:
  - group: ""
    resources: ["events"]
{% endif %}
# Don't log authenticated requests to certain non-resource URL paths.
- level: None
  userGroups: ["system:authenticated", "system:unauthenticated"]
  nonResourceURLs:
  - "/api*" # Wildcard matching.
  - "/version"
  - "/healthz"
  - "/readyz"
  - "/livez"
# exclude resources where the body is security-sensitive
- level: Metadata
  resources:
  - group: "authentication.k8s.io"
    resources: ["tokenreviews", "tokenrequests"]
# log request and response payloads for all write requests
- level: RequestResponse
  verbs:
  - update
  - patch
  - create
  - delete
  - deletecollection
# catch-all rule to log all other requests at the Metadata level.
- level: Metadata
  # Long-running requests like watches that fall under this rule will not
  # generate an audit event in RequestReceived.
  omitStages:
  - RequestReceived
  
{% endif %}
