# This policy allows outgoing network traffic from worker nodes to other IBM Cloud services.
# The example nets and ports in this policy are for IBM Cloud Container Registry, IBM Cloud
# Monitoring with Sysdig, IBM Log Analysis with LogDNA, and the managed Istio add-on.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-services
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 169.60.98.80/29
      - 169.62.37.240/29
      - 169.63.104.232/29
      - 169.47.153.160/28 
      # IBM Cloud Container Registry: UK South nets for your own registry
      - 141.125.71.136/29
      - 158.175.97.184/29
      - 158.176.105.64/29
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: UK South nets
      - 141.125.73.118/32
      - 141.125.78.188/32
      - 141.125.78.211/32
      - 158.175.125.163/32
      - 158.175.82.235/32
      - 158.175.98.206/32
      - 158.176.135.131/32
      - 158.176.85.107/32
      - 159.122.210.174/32
      - 169.62.37.240/29
      ports:
      - 6443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Log Analysis with LogDNA: EU GB nets
      - 141.125.78.186/32
      - 141.125.78.213/32
      - 158.175.125.165/32
      - 158.175.82.238/32
      - 158.176.135.132/32
      - 158.176.135.133/32
      ports:
      - 443
      - 80
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      ports:
      # Managed Istio add-on: Egress gateway
      - 80
      - 15443
    protocol: TCP
    source: {}
  ingress:
  - action: Allow
    destination:
      ports:
      # Managed Istio add-on: Ingress gateway and istiod control plane
      - 443
      - 853
      - 15010
      - 15012
      - 15014
      # Managed Istio add-on: Knative cluster local gateway
      - 80
      - 15021
      - 15443
    protocol: TCP
    source: {}
  order: 1800
  selector: ibm.role == 'worker_public'
  types:
  - Egress
  - Ingress
