apiVersion: v1
kind: ServiceAccount
metadata:
  name: submariner-calico-rpfilter-setter
  namespace: submariner-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: submariner-calico-rpfilter-scc-hostmount
  namespace: submariner-operator
subjects:
- kind: ServiceAccount
  name: submariner-calico-rpfilter-setter
  namespace: submariner-operator
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:hostmount
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: submariner-calico-rpfilter-scc-hostnetwork-v2
  namespace: submariner-operator
subjects:
- kind: ServiceAccount
  name: submariner-calico-rpfilter-setter
  namespace: submariner-operator
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork-v2
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: submariner-calico-rpfilter-setter
  namespace: submariner-operator
  annotations:
    description: "A run-once script to fix reverse path filtering issues with Submariner+Calico for CrossSubnet encapsulation"
spec:
  selector:
    matchLabels:
      app: submariner-calico-rpfilter-setter
  template:
    metadata:
      labels:
        app: submariner-calico-rpfilter-setter
    spec:
      hostNetwork: true
      serviceAccountName: submariner-calico-rpfilter-setter
      containers:
      - name: submariner-calico-rpfilter-setter
        image: alpine
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
          - sh
          - -c
          - |
            interface=$(ip route | grep default | head -1 | cut -d' ' -f5)
            nsenter --target 1 --mount \
              -- echo 2 > /proc/sys/net/ipv4/conf/${interface}/rp_filter
            echo "Read rp_filter value (which should be 2): $(cat /proc/sys/net/ipv4/conf/${interface}/rp_filter)"
            sleep 365d
      terminationGracePeriodSeconds: 1
